stages:
  - build
  - test

build_ubuntu_bionic:
  image: ubuntu:bionic
  stage: build
  script:
    - ./build-fMBT-packages-linux.sh
  artifacts:
    when: always
    paths:
      - debs/*
      - logs/*
      - test/*/*.txt

build_ubuntu_xenial:
  image: ubuntu:xenial
  stage: build
  script:
    - ./build-fMBT-packages-linux.sh
  artifacts:
    when: always
    paths:
      - debs/*
      - logs/*
      - test/*/*.txt

build_debian_stable:
  image: debian:latest
  stage: build
  script:
    - ./build-fMBT-packages-linux.sh
  artifacts:
    when: always
    paths:
      - debs/*
      - logs/*
      - test/*/*.txt

build_debian_unstable:
  image: debian:unstable
  stage: build
  script:
    - ./build-fMBT-packages-linux.sh
  artifacts:
    when: always
    paths:
      - debs/*
      - logs/*
      - test/*/*.txt

build_debian_testing:
  image: debian:testing
  stage: build
  script:
    - ./build-fMBT-packages-linux.sh
  artifacts:
    when: always
    paths:
      - debs/*
      - logs/*
      - test/*/*.txt

build_windows_64:
  image: fedora:23
  stage: build
  script:
    - ./build-fMBT-installer-winXX.exe.sh 64
  artifacts:
    paths:
    - build-win64/fMBT-installer*.exe

build_windows_32:
  image: fedora:23
  stage: build
  script:
    - ./build-fMBT-installer-winXX.exe.sh 32
  artifacts:
    paths:
    - build-win32/fMBT-installer*.exe

# test stages
test_ubuntu_bionic:
  image: ubuntu:bionic
  stage: test
  dependencies:
    - build_ubuntu_bionic
  services:
    - askervin/pythonshare-server
  script:
    - cd debs
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt install -f -y ./fmbt-pythonshare*.deb
    - pythonshare-client -C xyz@askervin-pythonshare-server --ls-remote

test_ubuntu_xenial:
  image: ubuntu:xenial
  stage: test
  dependencies:
    - build_ubuntu_xenial
  services:
    - askervin/pythonshare-server
  script:
    - cd debs
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt install -f -y ./fmbt-pythonshare*.deb
    - pythonshare-client -C xyz@askervin-pythonshare-server --ls-remote

test_debian_stable:
  image: debian:stable
  stage: test
  dependencies:
    - build_debian_stable
  services:
    - askervin/pythonshare-server
  script:
    - cd debs
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt install -f -y ./fmbt-pythonshare*.deb
    - pythonshare-client -C xyz@askervin-pythonshare-server --ls-remote

test_debian_unstable:
  image: debian:unstable
  stage: test
  dependencies:
    - build_debian_unstable
  services:
    - askervin/pythonshare-server
  script:
    - cd debs
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt install -f -y ./fmbt-pythonshare*.deb
    - pythonshare-client -C xyz@askervin-pythonshare-server --ls-remote

test_debian_testing:
  image: debian:testing
  stage: test
  dependencies:
    - build_debian_testing
  services:
    - askervin/pythonshare-server
  script:
    - cd debs
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt install -f -y ./fmbt-pythonshare*.deb
    - pythonshare-client -C xyz@askervin-pythonshare-server --ls-remote
