stages:
  - build

build_ubuntu_bionic:
  image: ubuntu:bionic
  stage: build
  script:
    - ./build-fMBT-packages-linux.sh
  artifacts:
    when: always
    paths:
      - debs/*
      - logs/*
      - test/*/*.txt

# disable trusty build for now, interactive test is failing
#build_ubuntu_trusty:
#  image: ubuntu:trusty
#  stage: build
#  script:
#    - ./build-fMBT-packages-linux.sh
#  artifacts:
#    when: always
#    paths:
#      - debs/*
#      - logs/*
#      - test/*/*.txt

build_ubuntu_xenial:
  image: ubuntu:xenial
  stage: build
  script:
    - ./build-fMBT-packages-linux.sh
  artifacts:
    when: always
    paths:
      - debs/*
      - logs/*
      - test/*/*.txt
build_debian_stable:
  image: debian:latest
  stage: build
  script:
    - ./build-fMBT-packages-linux.sh
  artifacts:
    when: always
    paths:
      - debs/*
      - logs/*
      - test/*/*.txt

build_debian_unstable:
  image: debian:unstable
  stage: build
  script:
    - ./build-fMBT-packages-linux.sh
  artifacts:
    when: always
    paths:
      - debs/*
      - logs/*
      - test/*/*.txt

build_debian_testing:
  image: debian:testing
  stage: build
  script:
    - ./build-fMBT-packages-linux.sh
  artifacts:
    when: always
    paths:
      - debs/*
      - logs/*
      - test/*/*.txt

build_windows_64:
  image: fedora:23
  stage: build
  script:
    - ./build-fMBT-installer-winXX.exe.sh 64
  artifacts:
    paths:
    - build-win64/fMBT-installer*.exe

build_windows_32:
  image: fedora:23
  stage: build
  script:
    - ./build-fMBT-installer-winXX.exe.sh 32
  artifacts:
    paths:
    - build-win32/fMBT-installer*.exe